language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - .jest
node_js:
  - lts/*
script:
  - yarn run test
  - yarn run build
  - yarn run size
after_success:
  - test $TRAVIS_BRANCH = "master" && yarn run doc
  - npx semantic-release@beta
  - yarn run report-coverage
